# Generated by Django 2.0.3 on 2018-04-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('createdDate', models.DateField()),
                ('createdBy', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
